# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Katie M. K. Blaede
author: Katie M. K. Blaede
email: hello@katiemkblaede.com
description: Design and illustration portfolio of Katie M. K. Blaede
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.katiemkblaede.com" # the base hostname & protocol for your site
twitter_username: katiemkblaede
github_username:  katiemkblaede

collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: /:collection/:path/

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

plugins:
  - jekyll-redirect-from
